services:
  twinbot_agent:
    container_name: twinbot_agent
    restart: unless-stopped
    image: twinbot_agent_img
    build: .
    env_file:
      - .env
    volumes:
      - ${SYSHOME}/twinbot/logs/:/app/logs/
    network_mode: "host"